"""
Django settings for boilerplate project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

from decouple import config


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def base_dir_join(*args):
    return os.path.join(BASE_DIR, *args)

APPS_DIR = base_dir_join('apps')


# MANAGER CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#admins
ADMINS = [
    ("""Admin""", 'contato@3ysoftwarehouse.com.br'),
]

# See: https://docs.djangoproject.com/en/dev/ref/settings/#managers
MANAGERS = ADMINS

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ewwhwaa-z+n!o+kq68#di5*gpuxe8k1v@8r9mqfl)3l!mjzynr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['testserver','127.0.0.1']

CSRF_COOKIE_SECURE=False
# Application definition

DJANGO_APPS = [
    # Default Django apps:
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Useful template tags:
    'django.contrib.humanize',

    # Admin
    'django.contrib.admin',
]

THIRD_PARTY_APPS = [
    'nested_admin',
    # 'silk',
]

# Apps specific for this project go here.
LOCAL_APPS = [
    # custom users app
    'apps.core',
    'apps.backoffice',
    'apps.common',
    'apps.dashboard',
    'apps.message_core',
    'apps.payment',
    'apps.service_core',
    'apps.lead_captation',
    'apps.customer',
    'apps.professional',
    'apps.api',
    'apps.after_sale',
    'apps.company_sale',
    'apps.chat1',

    # Your stuff: custom apps go here
]

# See: https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'silk.middleware.SilkyMiddleware',
]


ROOT_URLCONF = 'biuri.urls'

ADMIN_URL = r'^admin/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [base_dir_join('templates')],
        'APP_DIRS': True,

        'OPTIONS': {
            'libraries': {
                'template_tagcategory': 'apps.professional.templatetags.templatetag_category',
            },
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ]
        },
    },
]

WSGI_APPLICATION = 'biuri.wsgi.application'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = str(base_dir_join('staticfiles'))
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    base_dir_join('static'),
)

# MEDIA CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#media-root
MEDIA_ROOT = str(base_dir_join('media'))

# See: https://docs.djangoproject.com/en/dev/ref/settings/#media-url
MEDIA_URL = '/media/'


'''
SIMPLE HISTORY
'''

INSTALLED_APPS += ['simple_history',]

MIDDLEWARE_CLASSES += [
    'simple_history.middleware.HistoryRequestMiddleware',
]

'''
DJANGO REST FRAMEWORK
'''

INSTALLED_APPS += ['rest_framework',
                   'rest_framework.authtoken',
                   'rest_auth',
                   'django_filters',
                   'rest_framework_swagger',
                   'oauth2_provider',
                   'allauth',
                   'allauth.account',
                   'allauth.socialaccount',
                   'allauth.socialaccount.providers.facebook',
                   'allauth.socialaccount.providers.instagram',
                   ]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.SearchFilter',
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'PAGE_SIZE': 1000
}

LOGIN_REDIRECT_URL = '/dashboard'
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'basic': {
          "type": "apiKey",
          "name": "Authorization",
          "in": "header"
        }
    },
    'LOGIN_URL':'rest_framework:login',
    'LOGOUT_URL':'rest_framework:logout',
}

ADMIN_SITE_HEADER = "Administração da Biuri"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

OAUTH2_PROVIDER = {
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'},
    'ACCESS_TOKEN_EXPIRE_SECONDS': 60 * 60 * 24 * 180,
}

'''
EMAIL
'''

SITE_ID = 1

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

'''
CELERY
'''

CELERY_BROKER_URL = 'amqp://localhost'
CELERYBEAT_SCHEDULER = "djcelery.schedulers.DatabaseScheduler"

INSTALLED_APPS += (
    'django_celery_results',
    'django_celery_beat'
)

CELERY_RESULT_BACKEND = 'django-db'

# command start schedulers
## celery -A biuri beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

# command starts workers
## celery -A biuri worker -l info
##IUGU_ID PROD
##IUGU_ID = '09e3c17ee6df64a074e84e5d48a6fe61'
##IUGU_ID TEST
IUGU_ID ='3581508B030FB73A8E1A0DB2E2F910D09E59FE1024FE8AE9AC9EA35A5A9D0D07'

APP_OMIE_KEY = '486227180439'
APP_OMIE_SECRET = '31ce9d46b1c92786f9ebc47012e18e76'

SMS_TOKEN = 'exRD9u4aQdesmxgqw35ug8RhW2op9BdxMz28VTKS'

#
# SILKY_PYTHON_PROFILER = True
# SILKY_META = True

INSTALLED_APPS += ['django.contrib.admindocs']
ACCOUNT_UNIQUE_EMAIL = False
