# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0042_professional_gender_attendance'),
        ('customer', '0011_customer_avatar_image_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professionalvisualisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('profile', 'Perfil'), ('list', 'Listagem')], max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professional.Professional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
