# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180713_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalvisualisation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer'),
        ),
    ]
