# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180914_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalvisualisation',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_visualizations', to='service_core.Attendance'),
        ),
    ]
