# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='endereco',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='complemento',
            new_name='complement',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='ponto_referencia',
            new_name='reference_point',
        ),
    ]
