# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180131_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='uf',
            field=models.CharField(default='PE', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
