# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180604_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_covered',
            field=models.BooleanField(default=False),
        ),
    ]
