# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180828_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Neighborhood'),
        ),
    ]
