# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_neighborhood_father'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
