# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-25 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_core', '0049_auto_20180720_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=2000)),
                ('type', models.CharField(choices=[('professional', 'Profissional'), ('customer', 'Cliente')], max_length=20)),
                ('reason', models.CharField(choices=[('help', 'Dúvida'), ('quality', 'Pesquisa de satisfação'), ('complaint', 'Reclamação'), ('suggestion', 'Sugestão'), ('cancelation', 'Cancelamento'), ('new', 'Primeiro Atendimento')], max_length=40)),
                ('agendor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service_core.Attendance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
