# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='reason',
            field=models.CharField(choices=[('Dúvida', 'Dúvida'), ('Pesquisa de satisfação', 'Pesquisa de satisfação'), ('Reclamação', 'Reclamação'), ('Sugestão', 'Sugestão'), ('Cancelamento', 'Cancelamento'), ('Primeiro Atendimento', 'Primeiro Atendimento')], max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Profissional', 'Profissional'), ('Cliente', 'Cliente')], max_length=20),
        ),
    ]
