# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=8)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=120, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
