# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_auto_20180131_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('postal_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=120, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=120, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=120, null=True, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='address',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
