# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20180201_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=14, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=14, null=True, verbose_name='Latitude'),
        ),
    ]
