# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20180406_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(blank=True, default='Casa', max_length=20, verbose_name='Descricao Endereco'),
        ),
    ]
    
