# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_useraddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='ref_point',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ponto de Referencia'),
        ),
    ]
