# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0012_pricingcriterioncustomer'),
        ('core', '0010_auto_20180828_1736'),
        ('service_core', '0053_attendance_splits_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, max_length=200, null=True, verbose_name='Pacote')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição do pacote')),
                ('observation', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações sobre o pacote')),
            ],
            options={
                'verbose_name': 'Pacote',
            },
        ),
        migrations.CreateModel(
            name='BundleService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Quantidade')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Preço')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle', to='company_sale.Bundle', verbose_name='Pacote')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='service_core.Service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Pacote Serviço',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('state_registration', models.CharField(max_length=12, verbose_name='Inscrição Estadual')),
                ('company_name', models.CharField(max_length=30, verbose_name='Razão Social')),
                ('trading_name', models.CharField(max_length=30, verbose_name='Nome Fantasia')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='E-mail')),
                ('contact_name', models.CharField(max_length=30, verbose_name='Contato na Empresa')),
                ('contact_cellphone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone do Contato')),
                ('contact_email', models.CharField(blank=True, max_length=30, null=True, verbose_name='E-mail do Contato')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.Customer', verbose_name='Cliente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
    ]
