# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 17:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0067_auto_20181227_1644'),
        ('company_sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('commission', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Preço')),
                ('observation', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_bundle', to='company_sale.Bundle', verbose_name='Pacote')),
            ],
            options={
                'verbose_name': 'Sale',
            },
        ),
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company_sale.Company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='sale',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_executive', to='professional.Executive', verbose_name='Executivo'),
        ),
    ]
