# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0002_auto_20181227_1731'),
        ('professional', '0068_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='professional.Seller', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='company_sale.SaleStatus', verbose_name='Status'),
        ),
    ]
