# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 16:00
from __future__ import unicode_literals

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0003_auto_20181227_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='iugu_account_data',
            field=apps.common.fields.JSONField(default=dict, verbose_name='iugu account data'),
        ),
        migrations.AddField(
            model_name='company',
            name='iugu_account_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
