# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0004_auto_20190103_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.Customer', verbose_name='Cliente'),
        ),
    ]
