# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0005_auto_20181228_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='iugu_account_data',
            new_name='iugu_client_data',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='iugu_account_id',
            new_name='iugu_client_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(default='teste@teste.com.br', max_length=30, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
