# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0005_auto_20190103_1428'),
        ('company_sale', '0006_auto_20181228_1630'),
    ]

    operations = [
    ]
