# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 15:24
from __future__ import unicode_literals

import apps.common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0007_merge_20190103_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='information_data',
            field=apps.common.fields.JSONField(blank=True, default=dict, verbose_name='information_data'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.Customer', verbose_name='Cliente'),
        ),
    ]
