# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0010_auto_20190103_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_bundle', to='company_sale.Bundle', verbose_name='Pacote'),
        ),
    ]
