# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 14:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0013_auto_20190103_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='commission',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)], verbose_name='Comissão'),
        ),
    ]
