# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0014_auto_20190104_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salevouchergenerator',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_generator', to='company_sale.Sale', verbose_name='Venda'),
        ),
    ]
