# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0016_auto_20190107_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_executive', to='professional.Executive', verbose_name='Executivo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='professional.Seller', verbose_name='Vendedor'),
        ),
    ]
