# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0018_auto_20190107_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company_sale.Company', verbose_name='Empresa'),
        ),
    ]
