# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0019_auto_20190108_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company_sale.Company', verbose_name='Empresa'),
        ),
    ]
