# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20190108_1616'),
        ('company_sale', '0019_auto_20190108_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_sale.Sale', verbose_name='Venda')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Voucher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
