# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0020_auto_20190109_1624'),
        ('company_sale', '0020_vouchersale'),
    ]

    operations = [
    ]
