# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0021_merge_20190110_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('list_company', 'Can view list of companies'),), 'verbose_name': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('list_sale', 'Can view list of sales'),), 'verbose_name': 'Sale'},
        ),
    ]
