# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0024_auto_20190110_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale'},
        ),
    ]
