# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_sale', '0025_auto_20190110_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('list_sale', 'Can view list of sales'), ('edit_sale_seller', 'Can edit seller on Sale'), ('edit_sale_executive', 'Can edit executive on Sale')), 'verbose_name': 'Sale'},
        ),
    ]
