# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180828_1736'),
        ('message_core', '0002_auto_20180215_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=200)),
                ('cellphone', models.CharField(blank=True, max_length=13, null=True)),
                ('push_token', models.TextField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('push', 'PUSH NOTIFICATION'), ('whatsapp', 'WHATSAPP')], max_length=20)),
                ('is_success', models.BooleanField(default=False)),
                ('send', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='news',
            name='citys',
            field=models.ManyToManyField(blank=True, to='core.City'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='picture_client',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Picture Client'),
        ),
        migrations.AddField(
            model_name='news',
            name='public',
            field=models.CharField(choices=[('all', 'Todos'), ('professional', 'Profissional'), ('client', 'Cliente')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Picture Professional'),
        ),
    ]
