# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_core', '0003_auto_20190124_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='data',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
