# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_core', '0004_message_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='push_token',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('push', 'PUSH NOTIFICATION'), ('push_multiple', 'PUSH NOTIFICATION VÁRIOS'), ('whatsapp', 'WHATSAPP')], max_length=20),
        ),
    ]
