# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_core', '0005_auto_20190125_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='push_token',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='message',
            name='cellphone',
        ),
    ]
