# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_core', '0006_auto_20190125_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.TextField(blank=True, default='{}', max_length=5000, null=True),
        ),
    ]
