# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_core', '0007_auto_20190125_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('sms_multiple', 'SMS VÁRIOS'), ('push', 'PUSH NOTIFICATION'), ('push_multiple', 'PUSH NOTIFICATION VÁRIOS'), ('whatsapp', 'WHATSAPP')], max_length=20),
        ),
    ]
