# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0090_auto_20200517_1834'),
        ('core', '0012_neighborhood_zone'),
        ('service_core', '0063_auto_20200602_1845'),
        ('message_core', '0008_auto_20190125_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=200)),
                ('date_schedule', models.DateTimeField()),
                ('send_professional', models.BooleanField(default=False)),
                ('send_customer', models.BooleanField(default=False)),
                ('send_region', models.BooleanField(default=False)),
                ('has_sended', models.BooleanField(default=False)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professional.Executive')),
                ('neighborhoods', models.ManyToManyField(to='core.Neighborhood')),
                ('professional_categories', models.ManyToManyField(to='service_core.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
