# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_core', '0009_pushschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushschedule',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='professional.Executive'),
        ),
        migrations.AlterField(
            model_name='pushschedule',
            name='neighborhoods',
            field=models.ManyToManyField(blank=True, to='core.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='pushschedule',
            name='professional_categories',
            field=models.ManyToManyField(blank=True, to='service_core.Category'),
        ),
    ]
