# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_neighborhood_zone'),
        ('message_core', '0010_auto_20200609_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushScheduleCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.City', verbose_name='Cidade')),
                ('neighborhoods', models.ManyToManyField(to='core.Neighborhood', verbose_name='Bairros')),
            ],
        ),
        migrations.RemoveField(
            model_name='pushschedule',
            name='neighborhoods',
        ),
        migrations.AddField(
            model_name='pushschedule',
            name='cidades',
            field=models.ManyToManyField(to='core.City'),
        ),
        migrations.AddField(
            model_name='pushschedule',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('all', 'Masculino e Feminino'), ('male', 'Masculino'), ('female', 'Feminino')], max_length=20, null=True, verbose_name='Sexo dos Clientes'),
        ),
        migrations.AddField(
            model_name='pushschedule',
            name='professional_gender',
            field=models.CharField(blank=True, choices=[('all', 'Masculino e Feminino'), ('male', 'Masculino'), ('female', 'Feminino')], max_length=20, null=True, verbose_name='Sexo dos Profissionais'),
        ),
        migrations.AddField(
            model_name='pushschedulecity',
            name='push_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='message_core.PushSchedule'),
        ),
    ]
