# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_core', '0004_auto_20171113_1909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLead',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('rg', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('type', models.CharField(choices=[('Profissional', 'Profissional'), ('Executive', 'Executive')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20)),
                ('civil_status', models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Outro', 'Outro')], max_length=20)),
                ('birthdate', models.DateField(null=True)),
                ('telephone', models.CharField(blank=True, max_length=11)),
                ('celphone', models.CharField(blank=True, max_length=11)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.Address')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_core.Category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical lead',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('Profissional', 'Profissional'), ('Executive', 'Executive')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20)),
                ('civil_status', models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Outro', 'Outro')], max_length=20)),
                ('birthdate', models.DateField(null=True)),
                ('telephone', models.CharField(blank=True, max_length=11)),
                ('celphone', models.CharField(blank=True, max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutiveLead',
            fields=[
                ('lead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lead_captation.Lead')),
            ],
            options={
                'abstract': False,
            },
            bases=('lead_captation.lead',),
        ),
        migrations.CreateModel(
            name='ProfissionalLead',
            fields=[
                ('lead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lead_captation.Lead')),
            ],
            options={
                'abstract': False,
            },
            bases=('lead_captation.lead',),
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address'),
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.Category'),
        ),
    ]
