# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0003_auto_20171115_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='obs',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='lead',
            name='obs',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
