# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0004_auto_20171115_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='status',
            field=models.CharField(choices=[('Não Verificado', 'Não Verificado'), ('Não Aprovado', 'Não Aprovado'), ('Aprovado', 'Aprovado')], default='Não Verificado', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Não Verificado', 'Não Verificado'), ('Não Aprovado', 'Não Aprovado'), ('Aprovado', 'Aprovado')], default='Não Verificado', max_length=20),
        ),
    ]
