# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0005_auto_20171115_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
