# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0006_auto_20171115_1222'),
        ('lead_captation', '0004_auto_20171115_1547'),
    ]

    operations = [
    ]
