# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0005_auto_20171115_1248'),
        ('lead_captation', '0007_merge_20171115_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='type',
            field=models.CharField(choices=[('Profissional', 'Profissional'), ('Executive', 'Executive')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.ManyToManyField(to='service_core.Category'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('Profissional', 'Profissional'), ('Executive', 'Executive')], max_length=20),
        ),
    ]
