# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0008_auto_20171115_1728'),
        ('lead_captation', '0002_auto_20171115_1056'),
    ]

    operations = [
    ]
