# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0009_merge_20171115_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='type',
            field=models.CharField(choices=[('Profissional', 'Profissional'), ('Executive', 'Executive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('Profissional', 'Profissional'), ('Executive', 'Executive')], max_length=20),
        ),
    ]
