# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0010_auto_20171115_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='created',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
