# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0012_auto_20171117_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('', 'Estado civil'), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Sexo'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('', 'Estado civil'), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lead',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Sexo'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20),
        ),
    ]
