# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0013_auto_20171121_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
