# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0015_auto_20171121_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionallead',
            name='codigo_executivo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
