# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0016_profissionallead_codigo_executivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionallead',
            name='codigo_executivo',
        ),
    ]
