# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0018_auto_20171228_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.ManyToManyField(null=True, to='service_core.Category'),
        ),
    ]
