# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0020_auto_20180108_1950'),
        ('lead_captation', '0019_auto_20180103_1601'),
    ]

    operations = [
    ]
