# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0023_auto_20180713_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('Pendente de contato', 'Pendente de contato'), ('Contato realizado', 'Contato realizado')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.ManyToManyField(blank=True, to='service_core.Category'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('Pendente de contato', 'Pendente de contato'), ('Contato realizado', 'Contato realizado')], default='-', max_length=20),
        ),
    ]
