# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0024_auto_20181113_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('Pendente de contato', 'Pendente de contato'), ('Contato realizado', 'Contato realizado'), ('Visita agendada', 'Visita agendada'), ('Cadastro completo', 'Cadastro completo'), ('Ativado', 'Ativado'), ('Desvinculado', 'Desvinculado'), ('Sem interesse', 'Sem interesse')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('Pendente de contato', 'Pendente de contato'), ('Contato realizado', 'Contato realizado'), ('Visita agendada', 'Visita agendada'), ('Cadastro completo', 'Cadastro completo'), ('Ativado', 'Ativado'), ('Desvinculado', 'Desvinculado'), ('Sem interesse', 'Sem interesse')], default='-', max_length=20),
        ),
    ]
