# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-14 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0025_auto_20190110_1619'),
        ('lead_captation', '0025_auto_20190110_1616'),
    ]

    operations = [
    ]
