# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0026_merge_20190114_1642'),
        ('lead_captation', '0026_merge_20190114_1617'),
    ]

    operations = [
    ]
