# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-05 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0027_merge_20190125_1746'),
        ('lead_captation', '0027_merge_20190123_1913'),
    ]

    operations = [
    ]
