# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0028_merge_20190211_1728'),
        ('lead_captation', '0028_merge_20190205_1549'),
    ]

    operations = [
    ]
