# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-15 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0028_merge_20190205_1620'),
        ('lead_captation', '0029_merge_20190213_1505'),
    ]

    operations = [
    ]
