# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_captation', '0031_auto_20190520_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aniversário'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='celphone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('', 'Estado civil'), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Outro', 'Outro')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Sexo'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='rg',
            field=models.CharField(blank=True, max_length=11, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('Pendente de contato', 'Pendente de contato'), ('Contato realizado', 'Contato realizado'), ('Visita agendada', 'Visita agendada'), ('Cadastro completo', 'Cadastro completo'), ('Ativado', 'Ativado'), ('Desvinculado', 'Desvinculado'), ('Sem interesse', 'Sem interesse')], default='-', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aniversário'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.ManyToManyField(blank=True, to='service_core.Category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='celphone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('', 'Estado civil'), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Outro', 'Outro')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.Executive', verbose_name='Executivo'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Sexo'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='indicated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Indicado por'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='rg',
            field=models.CharField(blank=True, max_length=11, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('Pendente de contato', 'Pendente de contato'), ('Contato realizado', 'Contato realizado'), ('Visita agendada', 'Visita agendada'), ('Cadastro completo', 'Cadastro completo'), ('Ativado', 'Ativado'), ('Desvinculado', 'Desvinculado'), ('Sem interesse', 'Sem interesse')], default='-', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
    ]
