# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_campaign_executive'),
        ('lead_captation', '0032_auto_20190521_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payment.Campaign'),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Campaign', verbose_name='Campanha'),
        ),
    ]
