# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0010_auto_20171120_1716'),
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('average_time', models.PositiveIntegerField(default=0)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.Service')),
            ],
            options={
                'verbose_name': 'Service Professional',
            },
        ),
    ]
