# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0018_auto_20171227_1534'),
        ('professional', '0003_auto_20171213_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProfessionalPricingCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pricingcriterionoptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.PricingCriterionOptions')),
                ('service_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.ServiceProfessional')),
            ],
            options={
                'verbose_name': 'Service Professional',
            },
        ),
    ]
