# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_serviceprofessionalpricingcriterion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='professional',
        ),
        migrations.AlterModelOptions(
            name='serviceprofessionalpricingcriterion',
            options={'verbose_name': 'Service Professional Pricing Criterion'},
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
