# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0018_auto_20171227_1534'),
        ('professional', '0007_auto_20171227_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Badge'},
        ),
        migrations.AddField(
            model_name='professional',
            name='evaluations',
            field=models.ManyToManyField(related_name='evaluation_related', through='professional.ProfessionalEvaluation', to='service_core.Attendance'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_core.Attendance'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='badges',
            field=models.ManyToManyField(related_name='badges_related', through='professional.ProfessionalBadge', to='professional.Badge'),
        ),
    ]
