# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('professional', '0008_auto_20171227_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
    ]
