# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('professional', '0009_professional_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='citys',
            field=models.ManyToManyField(to='core.City'),
        ),
        migrations.AddField(
            model_name='professional',
            name='neighborhoods',
            field=models.ManyToManyField(to='core.Neighborhood'),
        ),
    ]
