# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0009_professional_iugu_account_data'),
        ('professional', '0010_auto_20180103_1945'),
    ]

    operations = [
    ]
