# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0027_auto_20180108_1950'),
        ('professional', '0011_merge_20180108_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_core.Category'),
        ),
    ]
