# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0014_remove_professional_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='professional/avatar/'),
        ),
    ]
