# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0015_professional_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='rating',
            field=models.PositiveIntegerField(default=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
