# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180103_1947'),
        ('professional', '0016_auto_20180128_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.City')),
                ('neighborhoods', models.ManyToManyField(to='core.Neighborhood')),
            ],
        ),
        migrations.RemoveField(
            model_name='professional',
            name='citys',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='neighborhoods',
        ),
        migrations.AddField(
            model_name='professionalcity',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professional.Professional'),
        ),
    ]
