# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0017_auto_20180128_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_core.Category', verbose_name='Área Principal'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição do profissional'),
        ),
    ]
