# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0018_auto_20180131_1528'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address'),
        ),
    ]
