# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0019_auto_20180131_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalcity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.City', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='professionalcity',
            name='neighborhoods',
            field=models.ManyToManyField(to='core.Neighborhood', verbose_name='Bairros'),
        ),
    ]
