# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_bankaccount'),
        ('professional', '0024_evaluationtype_description_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.BankAccount'),
        ),
    ]
