# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0027_auto_20180310_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='professional/avatar/'),
        ),
    ]
