# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0028_auto_20180319_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('provide_all_day', models.BooleanField(default=False)),
                ('dawn_morning', models.BooleanField(default=False)),
                ('afternoon_night', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('dawn_morning_range_begin', models.TimeField(default=datetime.time(0, 0))),
                ('dawn_morning_range_end', models.TimeField(default=datetime.time(0, 0))),
                ('afternoon_night_range_begin', models.TimeField(default=datetime.time(0, 0))),
                ('afternoon_night_range_end', models.TimeField(default=datetime.time(0, 0))),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Professional')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='professionalcategory',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categorys', to='professional.Professional'),
        ),
        migrations.AlterField(
            model_name='professionalcity',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='citys', to='professional.Professional'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules', to='professional.Professional'),
        ),
        migrations.AlterField(
            model_name='serviceprofessional',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='professional.Professional'),
        ),
        migrations.AlterField(
            model_name='serviceprofessionalpricingcriterion',
            name='service_professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_professional', to='professional.ServiceProfessional'),
        ),
    ]
