# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0029_auto_20180329_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='celphone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20, null=True),
        ),
    ]
