# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0030_auto_20180403_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalschedule',
            old_name='date',
            new_name='date_schedule',
        ),
    ]
