# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0036_auto_20180402_1754'),
        ('professional', '0031_auto_20180403_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cleaning', models.PositiveIntegerField(default=5)),
                ('punctuality', models.PositiveIntegerField(default=5)),
                ('accuracy', models.PositiveIntegerField(default=5)),
                ('observation', models.CharField(blank=True, max_length=2000, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.Attendance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
