# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0036_auto_20180402_1754'),
        ('core', '0007_auto_20180312_1527'),
        ('professional', '0032_evaluationcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='categorias',
            field=models.ManyToManyField(through='professional.ProfessionalCategory', to='service_core.Category'),
        ),
        migrations.AddField(
            model_name='professional',
            name='cidades',
            field=models.ManyToManyField(through='professional.ProfessionalCity', to='core.City'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professional_principal', to='service_core.Category', verbose_name='Área Principal'),
            preserve_default=False,
        ),
    ]
