# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0033_auto_20180409_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações sobre profissional'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='avatar',
            field=models.ImageField(blank=True, default='professional/avatar/default.png', upload_to='professional/avatar/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='celphone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
