# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0035_auto_20180411_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalScheduleDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('provide_all_day', models.BooleanField(default=False)),
                ('dawn_morning', models.BooleanField(default=False)),
                ('afternoon_night', models.BooleanField(default=False)),
                ('day_of_week', models.PositiveIntegerField(choices=[('0', 'SEGUNDA-FEIRA'), ('1', 'TERÇA-FEIRA'), ('2', 'QUARTA-FEIRA'), ('3', 'QUINTA-FEIRA'), ('4', 'SEXTA-FEIRA'), ('5', 'SÁBADO'), ('6', 'DOMINGO')])),
                ('dawn_morning_range_begin', models.TimeField(default=datetime.time(0, 0))),
                ('dawn_morning_range_end', models.TimeField(default=datetime.time(0, 0))),
                ('afternoon_night_range_begin', models.TimeField(default=datetime.time(0, 0))),
                ('afternoon_night_range_end', models.TimeField(default=datetime.time(0, 0))),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Professional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
