# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0037_auto_20180503_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalevaluation',
            name='customer_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalscheduledefault',
            name='afternoon_night_range_begin',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AlterField(
            model_name='professionalscheduledefault',
            name='afternoon_night_range_end',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AlterField(
            model_name='professionalscheduledefault',
            name='dawn_morning_range_begin',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='professionalscheduledefault',
            name='dawn_morning_range_end',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
