# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0040_auto_20180604_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
    ]
