# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0041_auto_20180604_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='gender_attendance',
            field=models.CharField(choices=[('all', 'Homem e Mulher'), ('male', 'Apenas Homem'), ('female', 'Apenas Mulher')], default='all', max_length=20, verbose_name='Sexos para atendimento'),
        ),
    ]
