# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0042_professional_gender_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
