# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 15:20
from __future__ import unicode_literals

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0044_auto_20180809_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='iugu_account_verification',
            field=apps.common.fields.JSONField(default=dict, verbose_name='iugu verification data'),
        ),
        migrations.AddField(
            model_name='professional',
            name='professional_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='professional_verified',
            field=models.BooleanField(default=False),
        ),
    ]
