# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0046_professional_iugu_account_id'),
        ('professional', '0047_professional_search_text'),
    ]

    operations = [
    ]
