# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0048_merge_20181113_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcustomer',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_evaluation_customer', to='service_core.Attendance'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='professionalevaluation',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluation_professional_attendance', to='service_core.Attendance'),
        ),
    ]
