# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0053_attendance_splits_number'),
        ('professional', '0050_professional_attendance_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_criterion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_core.PricingCriterion', verbose_name='Tem critério')),
                ('pricing_criterion_option', models.ManyToManyField(to='service_core.PricingCriterionOptions', verbose_name='Critérios')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pricing_criterions', to='professional.Professional')),
            ],
        ),
    ]
