# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0050_professional_attendance_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='cellphone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
