# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0052_auto_20181213_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofessionalpricingcriterion',
            name='average_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo Médio em minutos'),
        ),
    ]
