# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0053_auto_20181214_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'permissions': (('can_liberate_professional', 'Poder liberar um profissional para receber atendimentos'), ('can_edit_executive', 'Pode editar o executiveo relacionado ao profissional')), 'verbose_name': 'Professional'},
        ),
    ]
