# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0054_auto_20181214_1618'),
        ('professional', '0051_professionalcriterion'),
        ('professional', '0053_serviceprofessionalpricingcriterion_average_time'),
    ]

    operations = [
    ]
