# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180828_1736'),
        ('professional', '0055_merge_20181219_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.City', verbose_name='Cidade')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='citys', to='professional.Executive')),
            ],
        ),
        migrations.AddField(
            model_name='executive',
            name='cidades',
            field=models.ManyToManyField(through='professional.ExecutiveCity', to='core.City'),
        ),
    ]
