# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0056_auto_20181219_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='payment_frequency',
            field=models.CharField(choices=[(7, 'SEMANAL'), (15, 'QUINZENAL'), (30, 'MENSAL')], default=7, max_length=20, verbose_name='Dias de recebimento'),
        ),
    ]
