# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-21 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0059_executive_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, upload_to='professional/document/')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='professional.Professional')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='executive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='executive', to=settings.AUTH_USER_MODEL),
        ),
    ]
