# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0060_auto_20181221_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='professionaldocument',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Documentos', to='professional.Professional'),
        ),
    ]
