# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0061_auto_20181221_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaldocument',
            name='document',
            field=models.FileField(blank=True, default='professional/avatar/default.png', upload_to='professional/document/'),
        ),
    ]
