# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0062_auto_20181221_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='professionaldocument',
            name='document',
            field=models.FileField(default='professional/avatar/default.png', upload_to='professional/document/'),
        ),
        migrations.AlterField(
            model_name='professionaldocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_documento', to='professional.DocumentType'),
        ),
    ]
