# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0067_auto_20181227_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='cellphone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
