# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 15:21
from __future__ import unicode_literals

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0069_merge_20181228_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='iugu_account_data',
            field=apps.common.fields.JSONField(default=dict, verbose_name='iugu account data'),
        ),
        migrations.AddField(
            model_name='seller',
            name='iugu_account_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='iugu_account_verification',
            field=apps.common.fields.JSONField(default=dict, verbose_name='iugu verification data'),
        ),
    ]
