# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 15:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0070_auto_20181228_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='commission_percent',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
    ]
