# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0072_auto_20190107_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'permissions': (('list_seller', 'Can list sellers'), ('can_edit_executive', 'Can edit executive')), 'verbose_name': 'Vendedor'},
        ),
    ]
