# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0072_auto_20190107_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'permissions': (('can_liberate_professional', 'Poder liberar um profissional para receber atendimentos'), ('can_edit_executive', 'Pode editar o executivo relacionado ao profissional'), ('list_professional', 'Pode ver a Lista de Profissionais')), 'verbose_name': 'Professional'},
        ),
    ]
