# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-14 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0075_auto_20190111_1741'),
        ('professional', '0073_auto_20190110_1616'),
    ]

    operations = [
    ]
