# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0077_merge_20190123_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
