# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-05 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0077_merge_20190125_1746'),
        ('professional', '0077_merge_20190123_1913'),
    ]

    operations = [
    ]
