# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0078_merge_20190205_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=200, verbose_name='Contrato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('clause', models.CharField(default='', max_length=200, verbose_name='Cláusula')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Texto')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Contract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
