# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0081_auto_20190205_1703'),
        ('professional', '0079_merge_20190211_1728'),
    ]

    operations = [
    ]
