# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0084_auto_20190520_1647'),
        ('professional', '0084_auto_20190516_1628'),
    ]

    operations = [
    ]
