# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-13 23:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0085_merge_20190712_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='attendance_window',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(20)], verbose_name='Janela de tempo entre atendimentos'),
        ),
    ]
