# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-18 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0086_professional_attendance_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='professional_enabled_executive',
            field=models.BooleanField(default=True, verbose_name='Profissional Liberado pelo Executivo'),
        ),
    ]
