# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0087_professional_professional_enabled_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('Cadastro completo', 'Cadastro completo'), ('Ativado', 'Ativado'), ('Aprovado no Teste', 'Aprovado no Teste'), ('Reprovado no Teste', 'Reprovado no Teste'), ('Desvinculado', 'Desvinculado'), ('Sem interesse', 'Sem interesse')], default='-', max_length=20, verbose_name='Status'),
        ),
    ]
