# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0061_auto_20200218_1714'),
        ('professional', '0088_professional_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProfessionalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('maximum_price_old', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Preço Máximo')),
                ('minimum_price_old', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço (R$)')),
                ('average_time_old', models.PositiveIntegerField(default=0, verbose_name='Tempo Médio em minutos')),
                ('maximum_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Preço Máximo')),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço (R$)')),
                ('average_time', models.PositiveIntegerField(default=0, verbose_name='Tempo Médio em minutos')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_old', to='professional.Professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_professional_old', to='service_core.Service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Service Professional',
            },
        ),
    ]
