# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-17 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0089_serviceprofessionallog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprofessionallog',
            options={'verbose_name': 'Service Professional Log'},
        ),
    ]
