# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0090_auto_20200517_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(upload_to='professional/pictures/')),
                ('picture_thumbnail', models.ImageField(upload_to='professional/thumbnail/')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professional.Professional')),
            ],
            options={
                'verbose_name': 'Professional Picture',
            },
        ),
    ]
