# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-15 16:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0091_professionalpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='attendance_window',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(20)], verbose_name='Janela de tempo entre atendimentos'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nome Completo/Razão Social'),
        ),
    ]
