# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_address'),
        ('customer', '0003_customer_iugu_client_id'),
    ]

    operations = [
    ]
