# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customer_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/avatar/'),
        ),
    ]
