# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20180403_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_image_facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
