# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0048_cancelationreason_need_obs'),
        ('customer', '0011_customer_avatar_image_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCriterionCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer')),
                ('pricing_criterion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_core.PricingCriterion')),
                ('pricing_criterion_option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_core.PricingCriterionOptions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
