# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0002_historicalcategory_historicalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
