# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0004_auto_20171113_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
