# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0006_auto_20171116_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('Todos', 'Todos'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Todos', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='gender',
            field=models.CharField(choices=[('Todos', 'Todos'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Todos', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='gender',
            field=models.CharField(choices=[('Todos', 'Todos'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Todos', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.CharField(choices=[('Todos', 'Todos'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Todos', max_length=20),
        ),
    ]
