# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0007_auto_20171117_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='maximal_range_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='maximal_range_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='minimal_range_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='minimal_range_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='maximal_range_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='maximal_range_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='minimal_range_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='minimal_range_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
