# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0009_auto_20171117_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
