# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_serviceprofessional'),
        ('payment', '0002_creditcard'),
        ('customer', '0001_initial'),
        ('service_core', '0010_auto_20171120_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('scheduling_date', models.DateTimeField()),
                ('total_duration', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=45)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('pay_day', models.DateTimeField()),
                ('expected_date_checkout', models.DateTimeField()),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.CreditCard')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentForm')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Professional')),
            ],
            options={
                'verbose_name': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='AttendanceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.Attendance')),
            ],
            options={
                'verbose_name': 'Attendance Service',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Category'},
        ),
        migrations.AlterModelOptions(
            name='historicalservice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Service'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service'},
        ),
        migrations.AddField(
            model_name='attendanceservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.Service'),
        ),
    ]
