# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0011_auto_20171213_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalservice',
            old_name='maximal_range_price',
            new_name='mean_range_time',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='maximal_range_price',
            new_name='mean_range_time',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='maximal_range_time',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='minimal_range_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='maximal_range_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='minimal_range_time',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_core.Category'),
        ),
    ]
