# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0012_auto_20171213_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='checkout',
        ),
        migrations.AddField(
            model_name='attendance',
            name='canceled_date',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when=set(['canceled_by_customer', 'canceled_by_professional'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='completed_date',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when=set(['completed'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='confirmated_date',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when=set(['confirmated'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expired_date',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when=set(['expired'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='in_attendance_date',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when=set(['in_attendance'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='waiting_confirmation_date',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', null=True, when=set(['waiting_confirmation'])),
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='picture',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CreditCard'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='expected_date_checkout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='pay_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='payment_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentForm'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.Professional'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='scheduling_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
