# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0013_auto_20171219_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='on_transfer_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['on_transfer'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='canceled_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['canceled_by_customer', 'canceled_by_professional'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='completed_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['completed'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='confirmated_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['confirmated'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CreditCard'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='expected_date_checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='expired_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['expired'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='in_attendance_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['in_attendance'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='pay_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='payment_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentForm'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.Professional'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='waiting_confirmation_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['waiting_confirmation'])),
        ),
    ]
