# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:52
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0014_auto_20171219_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='waiting_customer_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['waiting_customer'])),
        ),
    ]
