# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0016_auto_20171219_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='initial_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_service', to='service_core.Service'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='services',
            field=models.ManyToManyField(related_name='attendace_services', through='service_core.AttendanceService', to='service_core.Service'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_administrate_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_duration',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='attendanceservice',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_relation', to='service_core.Attendance'),
        ),
    ]
