# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0017_auto_20171227_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCriterionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('pricing_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.PricingCriterion')),
            ],
            options={
                'verbose_name': 'Pricing Criterion Option',
            },
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='pricing_criterion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_core.PricingCriterion'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_core.PricingCriterion'),
        ),
    ]
