# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0018_auto_20171227_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
