# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0019_attendance_address_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='address',
        ),
    ]
