# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0020_remove_attendance_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='address_customer',
            new_name='address',
        ),
    ]
