# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0021_auto_20180104_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='canceled_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='confirmated_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='in_attendance_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='on_transfer_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='waiting_confirmation_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='waiting_customer_date',
        ),
    ]
