# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 18:37
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0022_auto_20180104_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='canceled_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['canceled_by_customer', 'canceled_by_professional'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='completed_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['completed'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='confirmated_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['confirmated'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expired_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['expired'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='in_attendance_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['in_attendance'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='on_transfer_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['on_transfer'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='waiting_confirmation_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['waiting_confirmation'])),
        ),
        migrations.AddField(
            model_name='attendance',
            name='waiting_customer_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when=set(['waiting_customer'])),
        ),
    ]
