# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0023_auto_20180104_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='modified',
        ),
    ]
