# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0025_auto_20180104_1542'),
        ('service_core', '0019_attendanceservice_quantity'),
    ]

    operations = [
    ]
