# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 22:50
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0026_merge_20180108_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='completed_date',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when=set(['completed'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='confirmated_date',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when=set(['confirmated'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='in_attendance_date',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when=set(['in_attendance'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='on_transfer_date',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when=set(['on_transfer'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='waiting_confirmation_date',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when=set(['waiting_confirmation'])),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='waiting_customer_date',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when=set(['waiting_customer'])),
        ),
    ]
