# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0027_auto_20180108_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='icon',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
