# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0029_auto_20180108_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='pricing_criterion_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_core.PricingCriterionOptions'),
        ),
    ]
