# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0032_auto_20180201_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='picture',
            new_name='picture_female',
        ),
        migrations.RenameField(
            model_name='historicalcategory',
            old_name='picture',
            new_name='picture_female',
        ),
        migrations.AddField(
            model_name='category',
            name='picture_male',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='picture_male',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
