# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0034_attendance_has_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
