# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0035_auto_20180402_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
