# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0036_auto_20180402_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_push_notificated',
            field=models.BooleanField(default=True),
        ),
    ]
