# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0039_attendance_is_sms_notificated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_sms_notificated',
            field=models.BooleanField(default=False),
        ),
    ]
