# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0039_auto_20180510_1647'),
        ('service_core', '0040_auto_20180411_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceProfessionalConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.Attendance')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Professional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
