# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_campaign_voucher'),
        ('service_core', '0043_attendance_has_evaluation_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Voucher'),
        ),
    ]
