# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0044_attendance_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='is_app_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_app_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
