# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0045_auto_20180601_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCancelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('obs', models.CharField(blank=True, max_length=1000, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.Attendance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancelationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('customer', 'customer'), ('professional', 'professional')], max_length=20)),
                ('is_rejection', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attendancecancelation',
            name='cancelation_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.CancelationReason'),
        ),
    ]
