# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0046_auto_20180611_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecancelation',
            name='is_rejection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancecancelation',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('professional', 'professional')], default='customer', max_length=20),
            preserve_default=False,
        ),
    ]
