# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0047_auto_20180611_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelationreason',
            name='need_obs',
            field=models.BooleanField(default=False),
        ),
    ]
