# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0048_cancelationreason_need_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='default_option',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_core.PricingCriterionOptions'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='has_pricing_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingcriterion',
            name='picture_female',
            field=models.ImageField(blank=True, null=True, upload_to='pricingcriterions/'),
        ),
        migrations.AddField(
            model_name='pricingcriterion',
            name='picture_male',
            field=models.ImageField(blank=True, null=True, upload_to='pricingcriterions/'),
        ),
        migrations.AddField(
            model_name='service',
            name='default_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_core.PricingCriterionOptions'),
        ),
        migrations.AddField(
            model_name='service',
            name='has_pricing_before',
            field=models.BooleanField(default=False),
        ),
    ]
