# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0052_attendance_total_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='splits_number',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
