# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0053_attendance_splits_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
