# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0054_attendance_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='can_set_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='can_set_price',
            field=models.BooleanField(default=True),
        ),
    ]
