# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-18 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0060_auto_20200205_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('', 'Não informado'), ('has_preference', 'Agendando Diretamente'), ('dont_has_preference', 'Peça Já')], default='', max_length=20),
        ),
    ]
