# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0062_attendance_pixel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceservice',
            name='duration',
            field=models.IntegerField(verbose_name='Duração (Minutos)'),
        ),
        migrations.AlterField(
            model_name='attendanceservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='attendanceservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='attendanceservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_core.Service', verbose_name='Serviço'),
        ),
    ]
