# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-15 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0064_auto_20200917_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.CreditCard', verbose_name='Cartão de Crédito'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Voucher', verbose_name='Cupom'),
        ),
    ]
