# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-25 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0069_auto_20210218_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='flexible_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 25, 12, 0), null=True, verbose_name='Horário final'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='flexible_date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 25, 8, 0), null=True, verbose_name='Horário inicial'),
        ),
    ]
