# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-28 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0070_auto_20210225_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='flexible_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário final'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='flexible_date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário inicial'),
        ),
    ]
