# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer'),
        ),
    ]
