# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:44
from __future__ import unicode_literals

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_creditcard_iugu_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_data',
            field=apps.common.fields.JSONField(default=dict, verbose_name='card data'),
        ),
    ]
