# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0033_auto_20180208_2305'),
        ('payment', '0005_creditcard_card_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('professional', 'professional'), ('marketplace', 'marketplace'), ('tax', 'tax'), ('executive', 'executive')], db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_core.Attendance')),
            ],
            options={
                'verbose_name': 'Transaction',
            },
        ),
    ]
