# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20180809_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=10, verbose_name='Número da Conta com dígito'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='agency',
            field=models.CharField(max_length=10, verbose_name='Agência com dígito'),
        ),
    ]
