# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0046_professional_iugu_account_id'),
        ('payment', '0015_auto_20180809_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transfer_iugu_id', models.CharField(max_length=40)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('accepted', 'Concluída'), ('rejected', 'Rejeitada')], default='pending', max_length=10)),
                ('observation', models.CharField(blank=True, max_length=300)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Professional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
