# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.Transfer'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.BankAccount'),
        ),
    ]
