# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20180810_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('total', 'total'), ('marketplace', 'marketplace')], db_index=True, default='total', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('professional', 'professional'), ('marketplace', 'marketplace'), ('tax', 'tax'), ('executive', 'executive'), ('discount', 'discount'), ('tax_interest', 'tax_interest')], db_index=True, max_length=20),
        ),
    ]
