# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_payment_paymentinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
