# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_auto_20181227_1540'),
        ('payment', '0021_auto_20181227_1644'),
    ]

    operations = [
    ]
