# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_core', '0053_attendance_splits_number'),
        ('payment', '0022_merge_20181228_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'percent'), ('value', 'value')], db_index=True, default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='voucher',
            name='has_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='quantity_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_core.Service'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='validation_type',
            field=models.CharField(choices=[('total', 'total'), ('marketplace', 'marketplace')], db_index=True, default='one_use', max_length=20),
        ),
    ]
