# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0084_auto_20190520_1647'),
        ('payment', '0027_auto_20190108_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.Executive', verbose_name='Executivo'),
        ),
    ]
