# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-13 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('Banco do Brasil', '001 - BANCO DO BRASIL S.A.'), ('Santander', '033 - BANCO SANTANDER (BRASIL) S.A.'), ('Bradesco', '036 - BANCO BRADESCO BBI S.A.'), ('Caixa Econômica', '104 - CAIXA ECONOMICA FEDERAL'), ('Itaú', '041 - BANCO ITAÚ S.A.'), ('Sicredi', '748 - BANCO COOPERATIVO SICREDI S.A.'), ('Sicoob', '756 - BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB'), ('Inter', 'BANCO INTER'), ('Neon', 'BANCO NEON'), ('Nubank', 'BANCO NUBANK'), ('Pagseguro', 'BANCO PAGSEGURO'), ('Banco Original', 'BANCO ORIGINAL')], max_length=100, verbose_name='Banco'),
        ),
    ]
