# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-09 11:45
from __future__ import unicode_literals

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_auto_20200606_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='information_data',
            field=apps.common.fields.JSONField(default=dict, verbose_name='information_data'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('accepted', 'Concluída'), ('rejected', 'Rejeitada'), ('refunded', 'Reembolsado')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_iugu_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
