# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-10-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_auto_20210115_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('Banco do Brasil', '001 - BANCO DO BRASIL S.A.'), ('Santander', '033 - BANCO SANTANDER (BRASIL) S.A.'), ('Bradesco', '036 - BANCO BRADESCO BBI S.A.'), ('Caixa Econômica', '104 - CAIXA ECONOMICA FEDERAL'), ('Itaú', '041 - BANCO ITAÚ S.A.'), ('Sicredi', '748 - BANCO COOPERATIVO SICREDI S.A.'), ('Sicoob', '756 - BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB'), ('Inter', 'BANCO INTER'), ('Neon', 'BANCO NEON'), ('Nubank', 'BANCO NUBANK'), ('Pagseguro', 'BANCO PAGSEGURO'), ('Banco Original', 'BANCO ORIGINAL'), ('Safra', 'BANCO SAFRA'), ('Modal', 'BANCO MODAL'), ('Banestes', 'BANCO BANESTES'), ('Money Plus', 'MONEY PLUS'), ('Mercantil do Brasil', 'BANCO MERCANTIL DO BRASIL'), ('Gerencianet', 'GERENCIANET PAGAMENTOS DO BRASIL'), ('Banrisul', 'BANCO BANRISUL'), ('BRB', 'BRB - BANCO DE BRASÍLIA'), ('Via Credi', 'BANCO VIA CREDI'), ('Unicred', 'UNICRED'), ('Next', 'NEXT BANK'), ('Agibank', 'BANCO AGIBANK S.A.'), ('Banpará', 'BANCO DO ESTADO DO PARÁ S.A. - BANPARÁ'), ('Votorantim', 'BANCO VOTORANTIM S.A.'), ('JP Morgan', 'Banco J.P. Morgan S.A.'), ('Banco C6', 'BANCO C6 S.A. - C6 Bank'), ('BS2', 'BANCO BS2 S.A.'), ('Banco Topázio', 'BANCO TOPÁZIO S.A.'), ('Uniprime', 'UNIPRIME CENTRAL CCC LTDA'), ('Stone', 'STONE PAGAMENTOS S.A.'), ('Banco Daycoval', 'BANCO DAYCOVAL S.A.'), ('Rendimento', 'BANCO RENDIMENTO S.A.'), ('Banco do Nordeste', 'BANCO DO NORDESTE DO BRASIL S.A.'), ('Citibank', 'BANCO CITIBANK S.A.'), ('PJbank', 'PJBANK'), ('Ccc Noroeste Brasileiro', 'COOPERATIVA CENTRAL DE CREDITO NOROESTE BRASILEIRO LTDA'), ('Uniprime Norte do Paraná', 'UNIPRIME NORTE DO PARANÁ'), ('Global SCM', 'GLOBAL SCM')], max_length=100, verbose_name='Banco'),
        ),
    ]
